site_name: Hide
site_url: https://docs.hide.sh
repo_url: https://github.com/hide-org/hide
repo_name: hide-org/hide
nav:
  - Home: 
    - index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Usage: 
    - usage/index.md
    - Projects: usage/projects.md
    - Tasks: usage/tasks.md
    - Files: usage/files.md
    - Search: usage/search.md
    - Git: usage/git.md
  - Tutorials:
    - tutorials/index.md
    - Langchain: tutorials/langchain.md
    - Autogen: tutorials/autogen.md
    - SWE-Agent: tutorials/swe-agent.md
  - Development: development.md
  - Contributing: CONTRIBUTING.md
  - API: api.md
theme: 
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/hide-logo.svg
  favicon: assets/hide-favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.highlight
    - content.code.copy
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:hello@hide.sh
    - icon: fontawesome/brands/github
      link: https://github.com/hide-org/hide
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/art_moskvin
copyright: Copyright &copy; 2024 Artem Moskvin
