/*
Daytona Server API

Testing ApiKeyAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package daytona

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/hide-org/hide/pkg/daytona"
)

func Test_daytona_ApiKeyAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ApiKeyAPIService GenerateApiKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var apiKeyName string

		resp, httpRes, err := apiClient.ApiKeyAPI.GenerateApiKey(context.Background(), apiKeyName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApiKeyAPIService ListClientApiKeys", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ApiKeyAPI.ListClientApiKeys(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApiKeyAPIService RevokeApiKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var apiKeyName string

		httpRes, err := apiClient.ApiKeyAPI.RevokeApiKey(context.Background(), apiKeyName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
