/*
Daytona Server API

Testing WorkspaceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package daytona

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/hide-org/hide/pkg/daytona"
)

func Test_daytona_WorkspaceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WorkspaceAPIService CreateWorkspace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WorkspaceAPI.CreateWorkspace(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspaceAPIService GetWorkspace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var workspaceId string

		resp, httpRes, err := apiClient.WorkspaceAPI.GetWorkspace(context.Background(), workspaceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspaceAPIService ListWorkspaces", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WorkspaceAPI.ListWorkspaces(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspaceAPIService RemoveWorkspace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var workspaceId string

		httpRes, err := apiClient.WorkspaceAPI.RemoveWorkspace(context.Background(), workspaceId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspaceAPIService SetProjectState", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var workspaceId string
		var projectId string

		httpRes, err := apiClient.WorkspaceAPI.SetProjectState(context.Background(), workspaceId, projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspaceAPIService StartProject", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var workspaceId string
		var projectId string

		httpRes, err := apiClient.WorkspaceAPI.StartProject(context.Background(), workspaceId, projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspaceAPIService StartWorkspace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var workspaceId string

		httpRes, err := apiClient.WorkspaceAPI.StartWorkspace(context.Background(), workspaceId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspaceAPIService StopProject", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var workspaceId string
		var projectId string

		httpRes, err := apiClient.WorkspaceAPI.StopProject(context.Background(), workspaceId, projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspaceAPIService StopWorkspace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var workspaceId string

		httpRes, err := apiClient.WorkspaceAPI.StopWorkspace(context.Background(), workspaceId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
