/*
Daytona Server API

Testing TargetAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package daytona

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/hide-org/hide/pkg/daytona"
)

func Test_daytona_TargetAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TargetAPIService ListTargets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TargetAPI.ListTargets(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TargetAPIService RemoveTarget", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var target string

		httpRes, err := apiClient.TargetAPI.RemoveTarget(context.Background(), target).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TargetAPIService SetDefaultTarget", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var target string

		httpRes, err := apiClient.TargetAPI.SetDefaultTarget(context.Background(), target).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TargetAPIService SetTarget", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.TargetAPI.SetTarget(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
