/*
Daytona Server API

Testing BuildAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package daytona

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/hide-org/hide/pkg/daytona"
)

func Test_daytona_BuildAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BuildAPIService CreateBuild", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BuildAPI.CreateBuild(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildAPIService DeleteAllBuilds", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.BuildAPI.DeleteAllBuilds(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildAPIService DeleteBuild", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var buildId string

		httpRes, err := apiClient.BuildAPI.DeleteBuild(context.Background(), buildId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildAPIService DeleteBuildsFromPrebuild", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var prebuildId string

		httpRes, err := apiClient.BuildAPI.DeleteBuildsFromPrebuild(context.Background(), prebuildId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildAPIService GetBuild", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var buildId string

		resp, httpRes, err := apiClient.BuildAPI.GetBuild(context.Background(), buildId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildAPIService ListBuilds", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BuildAPI.ListBuilds(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
