/*
Daytona Server API

Testing ProjectConfigAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package daytona

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/hide-org/hide/pkg/daytona"
)

func Test_daytona_ProjectConfigAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ProjectConfigAPIService DeleteProjectConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var configName string

		httpRes, err := apiClient.ProjectConfigAPI.DeleteProjectConfig(context.Background(), configName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectConfigAPIService GetDefaultProjectConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gitUrl string

		resp, httpRes, err := apiClient.ProjectConfigAPI.GetDefaultProjectConfig(context.Background(), gitUrl).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectConfigAPIService GetProjectConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var configName string

		resp, httpRes, err := apiClient.ProjectConfigAPI.GetProjectConfig(context.Background(), configName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectConfigAPIService ListProjectConfigs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ProjectConfigAPI.ListProjectConfigs(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectConfigAPIService SetDefaultProjectConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var configName string

		httpRes, err := apiClient.ProjectConfigAPI.SetDefaultProjectConfig(context.Background(), configName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectConfigAPIService SetProjectConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.ProjectConfigAPI.SetProjectConfig(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
